
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-eden}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_USER: ${POSTGRES_USER:-eden}
    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
volumes:
  database_data:
